name: "pre-commit checks"
description: "Runs pre-commit checks on repository"
runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v4

    # @todo [maintain] run pre-commit on everything after reformatting party
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v37
      with:
        since_last_remote_commit: true

    - name: Run pre-commit checks
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --show-diff-on-failure --files ${{ steps.changed-files.outputs.all_changed_files }}
