# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)(
      ^extern/|
      ^generated
      )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-json
      - id: check-executables-have-shebangs
      - id: detect-private-key # detects the presence of private keys.
      - id: fix-byte-order-marker # removes utf-8 byte order marker.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: requirements-txt-fixer # sorts entries in requirements.txt.

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.3
    hooks:
      - id: clang-format

  - repo: https://github.com/psf/black
    rev: "23.10.0"
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|yaml|yml|markdown|md)$

  - repo: https://github.com/dosisod/refurb
    rev: v1.22.1
    hooks:
      - id: refurb
        args: ["--ignore", "FURB179"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        name: flake8 (python)
        args: ["--max-line-length=120", "--extend-ignore=E203,E501"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint-fix

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck

  # @todo FS-1358 make PR to original maintainer's repo
  - repo: https://github.com/martukas/pre-commit-shfmt
    rev: d62fc8ef69bf91a0e452090a2af7070579f9d36c
    hooks:
      - id: shfmt
