# This step must be run in the Elroy software docker container
# https://github.com/elroyair/build_env
# which provides the alias `todo` to the following tool
# https://github.com/elroyair/todo-jira-linker

name: "Jira todos"
description: "Scrape todos and link them to Jira"
inputs:
  update-jira:
    required: true
    description: "Update Jira issues links and remove obsolete links"
    default: false
    options:
      - true
      - false
  branch:
    required: true
    description: "Git branch to use in reports to Jira"
runs:
  using: "composite"
  steps:
    - name: Scrape todos
      if: ${{ inputs.update-jira == 'false' }}
      shell: bash
      working-directory: .
      env:
        GIT_BRANCH_NAME: ${{ inputs.branch }}
      run: todo --good --bad

    - name: Scrape todos and update links
      if: ${{ inputs.update-jira == 'true' }}
      shell: bash
      working-directory: .
      env:
        GIT_BRANCH_NAME: ${{ inputs.branch }}
      run: todo --good --bad --link --clean
