name: Build & Test
# This workflow is responsible for building on all platform & build modes and running unit-tests.

on: [push]

# This work flow's job: build then test (sequential)
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: ghcr.io/elroyair/software_container_2204:main

    steps:
      - name: Safe Repository Work Around # see https://github.com/actions/checkout/issues/760
        run: |
          export GIT_CEILING_DIRECTORIES=/__w # only work before git v2.35.2
          git config --global --add safe.directory /__w/elroy_common_msg/elroy_common_msg
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_AUTOMATION_CLASSIC_PAT }}
          submodules: recursive
      - name: Set up conan to properly work with gcc (see https://docs.conan.io/en/latest/getting_started.html)
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Build and run unit tests
        run: ./scripts/run_tests.sh

  pre-commit:
    name: pre-commit checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run pre-commit checks
        uses: ./.github/workflows/pre-commit-checks

  todo-jira-linker:
    name: Jira todos
    runs-on: ubuntu-latest
    container: ghcr.io/elroyair/software_container_2204:main
    timeout-minutes: 5
    env:
      JIRA_USER: automation@elroyair.com
      JIRA_KEY: ${{ secrets.JIRA_AUTOMATION_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run todo-jira linker
        uses: ./.github/workflows/link-todo-jira
        with:
          branch: ${{ github.head_ref || github.ref_name }}
          update-jira: ${{ github.ref == 'refs/heads/main' }}
